<a href="https://colab.research.google.com/github/cristian966/ProyectPagWeb/blob/main/Netflix_Analysis1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#importar librerias
import pandas as pd

In [ ]:
#Declarar variables para guardar mi csv
netflix = pd.read_csv("netflix_titles.csv")

In [ ]:
#voy a consultar las primeras 5 filas de mi tabla, si añadimos el número nos mostrara el numero de tablas que hayamos puesto
netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
#consultar los tipos de datos diferentes que hay en mi tabla
netflix.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
# vamos a utilizar listas o arrays
lista_plataformas = ["netflix", "hbo", "disney"]
lista_plataformas[0]

'netflix'

In [ ]:
# cómo añadir otro elemento a mi lista/array
lista_plataformas.append("amazon")

In [ ]:
#imprimir mi lista/array
print(lista_plataformas)

['netflix', 'hbo', 'disney', 'amazon']

In [ ]:
# ver el tipo de dato de una variable
type(lista_plataformas)

list

In [ ]:
type(lista_plataformas)

list

In [ ]:
# voy a ordenar mi lista
lista_plataformas.sort()
print(lista_plataformas)

['amazon', 'disney', 'hbo', 'netflix']

In [ ]:
# Combinar métodos con atributos para odenarlo al reves
lista_plataformas.sort(reverse=True)
print(lista_plataformas)

['netflix', 'hbo', 'disney', 'amazon']

In [ ]:
# poner en mayusculas 
lista_plataformas[1].upper()

'HBO'

In [ ]:
#vamos a ver el uso de diccionarios
contenido_netflix = {
    "Movies": 6200,
    "Tv shows": 2350
}

In [ ]:
#Acceder a un valor del diccionario
contenido_netflix["Movies"]

6200

In [ ]:
#Redefinir el valor de una propiedad del diccionario
contenido_netflix["Movies"] = 6350

In [ ]:
#comprobar que ha cambiado  el valor de movies
print(contenido_netflix)

{'Movies': 6350, 'Tv shows': 2350}

In [ ]:
#Acceder a columnas y contar valores
#Atributo de normalize nos permite mostrar el conteo en porcentaje
#Para ordenar
paises = netflix["country"].value_counts(normalize = True, ascending = False)
print(paises)

United States                             0.353310
India                                     0.121866
United Kingdom                            0.052533
Japan                                     0.030717
South Korea                               0.024950
                                            ...
Romania, Bulgaria, Hungary                0.000125
Uruguay, Guatemala                        0.000125
France, Senegal, Belgium                  0.000125
Mexico, United States, Spain, Colombia    0.000125
United Arab Emirates, Jordan              0.000125
Name: country, Length: 748, dtype: float64

In [ ]:
#Analizar columnas con el metodo describe()
descripcion_directores = netflix["director"].describe()
print(descripcion_directores)

count              6173
unique             4528
top       Rajiv Chilaka
freq                 19
Name: director, dtype: object

In [ ]:
#ahora con numeros
descripcion_lanzamiento = netflix["release_year"].describe()
print(descripcion_lanzamiento)

count    8807.000000
mean     2014.180198
std         8.819312
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

In [ ]:
#Ordenar por valores de una columna
year_sort = netflix.sort_values(by = "release_year", ascending = True)
year_sort

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,TV-PG,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
...,...,...,...,...,...,...,...,...,...,...,...,...
862,s863,TV Show,Special,NaN,"Ryan O'Connell, Jessica Hecht, Punam Patel, Ma...",United States,"May 20, 2021",2021,TV-MA,2 Seasons,TV Comedies,A young gay man with cerebral palsy branches o...
861,s862,Movie,Little Singham Future mein Satakli,Prakash Satam,"Anamaya Verma, Ganesh Divekar, Jigna Bharadhwa...",NaN,"May 20, 2021",2021,TV-Y7,47 min,"Children & Family Movies, Comedies",Little Singham and his crew travel to the year...
857,s858,TV Show,The Neighbor,NaN,"Quim Gutiérrez, Clara Lago, Adrián Pino, Catel...",Spain,"May 21, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",Self-centered Javier's life gets a bit messy w...
876,s877,TV Show,Alma Matters,NaN,NaN,India,"May 14, 2021",2021,TV-MA,1 Season,"Docuseries, International TV Shows",Alumni of India’s elite academic institutes sh...
965,s966,TV Show,Yasuke,NaN,"LaKeith Stanfield, Takehiro Hira, Maya Tanida,...",NaN,"April 29, 2021",2021,TV-MA,1 Season,"Anime Series, International TV Shows",A peaceful boatman once known as the Black Sam...

In [ ]:
#Ordenar por indice(id)
year_sort_index = netflix.sort_index(ascending = False)
year_sort_index

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
...,...,...,...,...,...,...,...,...,...,...,...,...
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."

In [ ]:
#Acceder a ciertas filas y columnas
netflix.iloc[[0,1,2,3],[0,1,2,3,4]]

,show_id,type,title,director,cast
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi..."
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN

In [ ]:
#Acceder a filas y columnas por rangos
netflix.iloc[0:20, 1:6]

,type,title,director,cast,country
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India
5,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN
6,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN
7,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin..."
8,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom
9,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States
10,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN
11,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN
12,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic"
13,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN
14,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN
15,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States
16,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN
17,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico
18,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN
19,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN